import type { NextPage } from 'next'
import Head from 'next/head'
import MainNav from '../components/MainNav'
import Footer from '../components/Footer'
import SwipSlider from '../components/SwipSlider'
import Image from 'next/image'
import ethereum_img from '../static/svgs/ethereum.svg'
import nft1 from "../static/nfts/nft1.png"
import nft2 from "../static/nfts/nft2.png"
import nft3 from "../static/nfts/nft3.png"
import nft4 from "../static/nfts/nft4.png"
import nft5 from "../static/nfts/nft5.png"
import nft6 from "../static/nfts/nft6.png"
import nft7 from "../static/nfts/nft7.png"
import nft8 from "../static/nfts/nft8.png"
import nft9 from "../static/nfts/nft9.png"
import nft10 from "../static/nfts/nft10.png"
import nft11 from "../static/nfts/nft11.png"
import avax_img from '../static/svgs/avax.svg'
import fantom_img from '../static/svgs/fantom.svg'
import polygon_img from '../static/svgs/polygon.svg'

import { AccordionPrice } from '../components/AccordionPrice'
import { faGlobe, faPlus } from '@fortawesome/free-solid-svg-icons'
import { faDiscord } from '@fortawesome/free-brands-svg-icons/faDiscord'
import { faTwitter } from '@fortawesome/free-brands-svg-icons/faTwitter'

import greg_img from "../static/greg.png"
import verified_img from "../static/verified.png"

import Link from 'next/link'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const Explorer: NextPage = () => {

  return (
    <div className="w-full container p-8 overflow-hidden">
      <Head>
        <title>Omni-X Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainNav header='Explorer' />
      
      <div className="w-full flex-col items-center pt-[80px] lg:pt-[150px] px-32">
        <div
          className="m-auto flex w-full flex-col lg:flex-row bg-collection"
        >
            <Image
                src={nft1}
                width={160}
            />
            <div className='w-full flex flex-col mx-6 my-2'>
                <div className='flex flex-row'>
                    <p className='text-2xl font-bold roboto mr-6'>BORED APE YACHT CLUB</p>
                    <Image
                        src={verified_img}
                        alt="Is verified"
                    />
                </div>
                <div className='flex flex-row mt-4'>
                    <div className='flex flex-col w-1/6'>
                        <p className='text-underline font-bold'>items</p>
                        <p className='font-bold'>10,000</p>
                    </div>
                    <div className='flex flex-col w-1/6'>
                        <p className='text-underline font-bold'>holders</p>
                        <p className='font-bold'>6.3k</p>
                    </div>
                    <div className='flex flex-col w-1/6'>
                        <p className='text-underline font-bold'>floor</p>
                        <p className='font-bold'>
                            <span className='mr-2'>86.50</span>
                            <Image
                                src={ethereum_img}
                                className="w-6 md:w-auto"
                                alt="Ethereum"
                                width={16}
                                height={16}
                            />
                        </p>
                    </div>
                    <div className='flex flex-col w-1/6'>
                        <p className='text-underline font-bold'>sales tax</p>
                        <p className='font-bold'>5%</p>
                    </div>
                </div>
            </div>
            <div className='flex flex-col mr-4'>
                <button className="focus:outline-none mt-auto w-full text-grey-400 border-gray-400 rounded-full border font-semibold raleway bg-grey-200 hover:bg-grey-800 focus:ring-4 focus:ring-grey-300 font-medium text-sm p-2 md:px-5 md:py-2.5 mb-2 dark:bg-grey-600 dark:hover:bg-grey-700 dark:focus:ring-grey-900 ml-auto mr-auto">
                    <FontAwesomeIcon
                        icon={faPlus}
                        className="mr-4"
                    />
                    watchlist
                </button>
                <div className='flex flex-row justify-between items-center mb-auto'>
                    <Link
                        href="/"
                    >
                        <a>
                            <FontAwesomeIcon
                                icon={faDiscord}
                                className="text-grey-400 mr-4"
                                fontSize={30}
                            />
                        </a>
                    </Link>
                    <Link
                        href="/"
                    >
                        <a>
                            <FontAwesomeIcon
                                icon={faTwitter}
                                className="text-grey-400 mr-4"
                                fontSize={30}
                            />
                        </a>
                    </Link>
                    <Link
                        href="/"
                    >
                        <a>
                            <FontAwesomeIcon
                                icon={faGlobe}
                                className="text-grey-400"
                                fontSize={30}
                            />
                        </a>
                    </Link>
                </div>
            </div>
        </div>
      </div>
      <div className="w-full flex-col items-center pt-20">
        <div
          className="m-auto flex w-full flex-col lg:flex-row"
        >
            <div className='w-[300px]'></div>
            <div className='w-full'>
                <button className='w-[160px] text-xl font-bold'>items</button>
                <button className='w-[160px] text-xl font-bold'>activity</button>
                <button className='w-[160px] text-xl font-bold'>stats</button>
            </div>
        </div>
      </div>
      <div className='w-full flex-col items-center'>
        <div
          className="m-auto flex w-full flex-col lg:flex-row"
        >
            <div className='w-[300px] border border-2 flex flex-col hide-scrollbar overflow-auto' style={{height: 'calc(100vh - 23rem - 2px)', maxHeight: 'calc(100vh - 23rem - 2px)'}}>
                <div className='w-full flex flex-row px-4 py-2 border-b-2 justify-between items-center'>
                    <p className='text-gray-500 font-semibold text-lg'>Buy Now</p>
                    <div className="form-check form-switch ml-auto mt-auto mb-auto">
                        <input className="form-check-input appearance-none w-9 -ml-10 rounded-full float-left h-5 align-top bg-white bg-no-repeat bg-contain bg-gray-300 focus:outline-none cursor-pointer shadow-sm" type="checkbox" role="switch" id="flexSwitchCheckDefault56" />
                    </div>
                </div>
                <div className='w-full border-b-2'>
                    <AccordionPrice title="Price" />
                </div>
                <div className='w-full border-b-2'>
                    <AccordionPrice title="Blockchain" />
                </div>
                <div className='w-full border-b-2'>
                    <AccordionPrice title="Rarity" />
                </div>
                <div className='w-full border-b-2'>
                    <AccordionPrice title="Attributes" />
                </div>
            </div>
            <div className='w-full border-t-2 overflow-auto hide-scrollbar' style={{height: 'calc(100vh - 23rem - 2px)', maxHeight: 'calc(100vh - 23rem - 2px)'}}>
                <div className='w-full max-w-full flex flex-row collection-items px-10 py-6'>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft2}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft3}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft4}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft5}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft6}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft7}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft8}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft9}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft10}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                    <div className='collection-item flex flex-col'>
                        <Image
                            src={nft11}
                            className="w-full h-auto"
                        />
                        <span className='text-gray-400 text-sm py-2 font-semibold'>BoredApeYachtClub #6583</span>
                        <div className='flex flex-row w-full'>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={32}
                                height={32}
                            />
                            <span className='ml-2 w-full'>85.65</span>
                            <div className='ml-auto counts-div flex'>
                                <span className='ml-auto mr-4 text-ms font-bold' style={{marginTop: '2px'}}>4132</span>
                            </div>
                        </div>
                        <div className='flex flex-row w-full'>
                            <span className='text-gray-400 text-ms mr-4'>accepts: </span>
                            <Image
                                src={ethereum_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={avax_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={polygon_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                            <Image
                                src={fantom_img}
                                className="w-3 h-auto"
                                width={12}
                                height={12}
                            />
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  )
}

export default Explorer