import type { NextPage } from 'next'
import Head from 'next/head'
import MainNav from '../components/MainNav'
import Footer from '../components/Footer'
import SwipSlider from '../components/SwipSlider'
import Image from 'next/image'
import ethereum_img from '../static/svgs/ethereum.svg'
import avax_img from '../static/svgs/avax.svg'
import arbitrum_img from '../static/svgs/arbitrum.svg'
import binance_img from '../static/svgs/binance.svg'
import optimism_img from '../static/svgs/optimism.svg'
import polygon_img from '../static/svgs/polygon.svg'
import fantom_img from '../static/svgs/fantom.svg'
import omni_img from "../static/omni.png"
import greg_img from "../static/greg.png"

const Home: NextPage = () => {
  return (
    <div className="w-full container p-8 overflow-hidden">
      <Head>
        <title>Omni-X Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainNav />
      
      <div className="w-full flex-col items-center pt-[80px] lg:pt-[150px]">
        <div
          className="m-auto flex w-full flex-col lg:pb-20 lg:pl-20 lg:pr-20 lg:flex-row"
        >
          <div className="raleway w-full px-4 py-0 font-medium lg:w-4/6 lg:px-6 lg:py-16">
            <p className="m-0  text-justify text-5xl lg:text-left">
              Mint, Transact, & Transfer
              NFTs from Any Network.
            </p>
            <div className="w-full flex flex-row pt-12 pb-12">
              <Image
                src={ethereum_img}
                className="w-6 md:w-auto"
                alt="Ethereum"
              />
              <Image
                src={avax_img}
                className="w-6 md:w-auto"
                alt="Avax"
              />
              <Image
                src={arbitrum_img}
                className="w-6 md:w-auto"
                alt="Arbitrum"
              />
              <Image
                src={binance_img}
                className="w-6 md:w-auto"
                alt="Binance"
              />
              <Image
                src={optimism_img}
                className="w-6 md:w-auto"
                alt="Optimism"
              />
              <Image
                src={polygon_img}
                className="w-6 md:w-auto"
                alt="Polygon"
              />
              <Image
                src={fantom_img}
                className="w-6 md:w-auto"
                alt="Fantom"
              />
            </div>
            <p className="m-0 text-justify text-2xl lg:text-left">
              OmniX is the first multichain NFT Marketplace powered by LayerZero              
            </p>
          </div>
          <div className="flex w-full flex-col items-center px-10 py-5 lg:w-2/6 lg:items-end">
            <Image
              src={omni_img}
              className="w-48 sm:w-96 md:w-auto h-auto"
            />
          </div>
        </div>
      </div>
      <div className="w-full flex-col items-center">
        <div
          className="m-auto flex w-full flex-collg:flex-row greg-panel p-12 md:p-24 lg:px-40"
        >
          <div className='flex flex-col w-full px-4 lg:w-4/6 p-20 lg:py-40 xl:p-32 xl:px-20 2xl:px-40'>
            <p className="m-0  text-justify text-sm md:text-xl lg:text-2xl xl:text-4xl lg:text-left text-white raleway font-bold lg:pb-8">
              Greg.
            </p>
            <p className="m-0  text-justify text-sm md:text-xl lg:text-3xl xl:text-5xl lg:text-left text-white raleway lg:pb-4">
              The Genesis
            </p>
            <p className="m-0  text-justify text-sm md:text-xl lg:text-3xl xl:text-5xl lg:text-left text-white raleway font-semibold lg:pb-4">
              OMNIVERSE
            </p>
            <p className="m-0  text-justify text-sm md:text-xl lg:text-3xl xl:text-5xl lg:text-left text-white raleway lg:pb-16">
              NFT Collection
            </p>
            <button className="focus:outline-none text-white font-semibold raleway bg-pink-600 hover:bg-pink-800 focus:ring-4 focus:ring-pink-300 font-medium rounded-lg text-sm p-2 md:px-5 md:py-2.5 mr-2 mb-2 dark:bg-pink-600 dark:hover:bg-pink-700 dark:focus:ring-pink-900 lg:ml-16 mr-auto">learn more</button>
          </div>
          <div className="flex m-auto flex-col items-center lg:w-3/6 px-10 xl:px-20 2xl:px-32 lg:items-end hidden md:block">
            <Image
              src={greg_img}
              className="w-auto h-auto m-auto" 
            />
          </div>
        </div>
      </div>
      <div className="w-full flex-col items-center">
        <div
          className="m-auto flex w-full flex-collg:flex-row p-12 md:p-24 pb-40"
        >
          <p className="m-0 text-justify text-xl lg:text-2xl xl:text-4xl lg:text-left raleway font-bold lg:pb-8">
          Featured Collections
          </p>
        </div>
        <SwipSlider/>
      </div>

      <Footer />
    </div>
  )
}

export default Home
